version: '3.7'
services:
  api:
    build:
      context: ./back
      target: build
    ports:
      - 3000:3000
    volumes:
      - ./back:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev