#Build stage
FROM node:16-alpine AS build

WORKDIR /app

COPY package*.json .

RUN npm install
RUN npm i express
RUN npm i @types/express typescript ts-node-dev rimraf --save-dev

COPY . .

RUN npx tsc --init

RUN npm run build

#Production stage+
FROM node:16-alpine AS production

WORKDIR /app

COPY package*.json .

RUN npm ci --only=production

COPY --from=build /app/dist ./dist

CMD ["node", "dist/index.js"]